### ISSUE TITLE
Extract the common content and faq widgets to afya_moja_core

### ISSUE THREAD

**Issue by EugeneDevv** [savannahghi/afyamoja#386]

**Comment by abiudrn** [comment]
https://github.com/savannahghi/afyamoja/pull/385#discussion_r873119164

**Comment by abiudrn** [comment]
https://github.com/savannahghi/afyamoja/pull/385#discussion_r873119206

**Comment by abiudrn** [comment]
https://github.com/savannahghi/afyamoja/pull/385#discussion_r873119405

**Comment by abiudrn** [comment]
https://github.com/savannahghi/afyamoja/pull/385#discussion_r873119450

**Comment by abiudrn** [comment]
https://github.com/savannahghi/afyamoja/pull/385#discussion_r873119579

**Comment by abiudrn** [comment]
https://github.com/savannahghi/afyamoja/pull/385#discussion_r873119635
